# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-23 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=30)),
                ('image_description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('image_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bag.category')),
            ],
        ),
    ]
